parameters:
#    my_company_hello.example.class: MyCompany\HelloBundle\Example

services:
#    my_company_hello.example:
#        class: %my_company_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
